state-path: state.pickle

ingestion:
  enabled: true
  sources:
    - name: "source1"
      type: "git"
      enabled: true
      path: ~/src/repo
      ingestion-limit: 100
      remote: origin
      branches:
        - master
        - release-*

    - name: "source2"
      type: "bitbucket"
      url: https://api.bitbucket.org
      username: user
      password: pass
      workspace: workspace
      projects:
        - name: project1
          repositories:
            - name: repo1
            - name: repo2

    - name: "jira"
      type: "jira"
      url: https://YOUR.atlassian.net/
      ingestion-limit: 1000
      username: username@domain.com
      password: ACCESS_TOKEN

reports:
  - name: overview
    type: overview
    out-path: reports/overview.html

  - name: overview-filtered
    type: overview
    enabled: true
    out-path: reports/overview-filtered.html
    filter: "'John' in user"

  - name: overview-tz-normalized
    type: overview
    timezone: "Europe/Amsterdam"
    out-path: reports/overview-2.html

  - name: per-user-stats
    type: per-user-stats
    out-dir: reports/per-user-stats

  - name: per-source-stats
    type: per-source-stats
    out-dir: reports/per-source-stats

  - name: pr-reviews
    type: pr-reviews
    out-path: pr-reviews.html

  - name: word-clouds
    type: word-clouds
    grouping-period: Q
    width: 1400
    height: 800
    max-words: 250
    stop-words:
      - "a"
      - "an"
      - "and"
      - "be"
      - "for"
      - "from"
      - "http"
      - "https"
      - "in"
      - "is"
      - "it"
      - "of"
      - "on"
      - "or"
      - "that"
      - "the"
      - "this"
      - "to"
    out-path: word-clouds.html

  - name: internal-state
    type: internal-state
    out-path: internal-state.html

  - name: datasets-export
    type: datasets-export
    out-dir: datasets
