state-path: state.pickle

ingestion:
  enabled: true
  sources:
    - name: "source1"
      type: "git"
      enabled: true
      path: ~/src/repo
      ingestion-limit: 100
      remote: origin
      branches:
        - master
        - release-*

    - name: "source2"
      type: "bitbucket"
      url: https://api.bitbucket.org
      username: user
      password: pass
      workspace: workspace
      projects:
        - name: project1
          repositories:
            - name: repo1
            - name: repo2

    - name: "jira"
      type: "jira"
      url: https://YOUR.atlassian.net/
      ingestion-limit: 1000
      username: username@domain.com
      password: ACCESS_TOKEN

reports:
  - name: overview
    type: overview
    out-path: overview.html

  - name: overview-filtered
    type: overview
    enabled: true
    out-path: overview-filtered.html
    filter: "'John' in author"

  - name: overview-tz-normalized
    type: overview
    timezone: "Europe/Amsterdam"
    out-path: overview-2.html

  - name: user-contributions
    type: user-contributions
    dir-path: contributions

  - name: per-source-stats
    type: per-source-stats
    dir-path: per-source-stats

  - name: word-clouds
    type: word-clouds
    grouping-period: Q
    width: 1200
    height: 800
    out-path: word-clouds.html

  - name: internal-state
    type: internal-state
    out-path: internal-state.html
