state-path: state.pickle

sources:
  - name: "source1"
    type: "git"
    path: ~/src/repo
    ingestion-limit: 100
    branches:
      - master

  - name: "source2"
    type: "bitbucket"
    url: https://api.bitbucket.org
    username: user
    password: pass
    workspace: workspace
    projects:
      - name: project1
        repositories:
          - name: repo1
          - name: repo2

reports:
  - name: overview
    type: overview
    out-path: overview.html